function toggleSwitch(){var a=document.getElementById("agentLocation").value,c=document.getElementById("dataDtConfig").value;chrome.storage.local.get("dynaTraceUEMSwitch",function(b){0==b.dynaTraceUEMSwitch||null==b.dynaTraceUEMSwitch?(chrome.storage.local.set({dynaTraceUEMSwitch:1}),chrome.storage.local.set({agentLocation:a}),chrome.storage.local.set({dtConfig:c}),document.getElementById("status").innerHTML="Injection On",document.getElementById("status").style.color="green"):(chrome.storage.local.set({dynaTraceUEMSwitch:0}),
document.getElementById("status").innerHTML="Injection Off",document.getElementById("status").style.color="red")})}chrome.storage.local.get("dynaTraceUEMSwitch",function(a){0==a.dynaTraceUEMSwitch||null==a.dynaTraceUEMSwitch?(document.getElementById("status").innerHTML="Injection Off",document.getElementById("status").style.color="red"):(document.getElementById("status").innerHTML="Injection On",document.getElementById("status").style.color="green")});
function setTextBoxDefaults(){chrome.storage.local.get("agentLocation",function(a){null==a.agentLocation?(document.getElementById("agentLocation").value="Not Set",document.getElementById("agentLocationForm").value="Not Set"):(document.getElementById("agentLocation").value=a.agentLocation,document.getElementById("agentLocationForm").value=a.agentLocation)});chrome.storage.local.get("dtConfig",function(a){null==a.dtConfig?(document.getElementById("dataDtConfig").value="Not Set",document.getElementById("dataDtConfigForm").value=
"Not Set"):(document.getElementById("dataDtConfig").value=a.dtConfig,document.getElementById("dataDtConfigForm").value=a.dtConfig)})}document.addEventListener("DOMContentLoaded",function(){document.getElementById("agentLocationForm").addEventListener("click",function(){document.getElementById("agentLocationForm").select()})});document.addEventListener("DOMContentLoaded",function(){document.getElementById("dataDtConfigForm").addEventListener("click",function(){document.getElementById("dataDtConfigForm").select()})});
document.addEventListener("DOMContentLoaded",function(){document.getElementById("fullDtConfig").addEventListener("click",function(){document.getElementById("fullDtConfig").select()})});document.addEventListener("DOMContentLoaded",function(){document.getElementById("htmlHostname").addEventListener("click",function(){document.getElementById("htmlHostname").select()})});document.addEventListener("DOMContentLoaded",function(){document.getElementById("bootstrapHostname").addEventListener("click",function(){document.getElementById("bootstrapHostname").select()})});
document.addEventListener("DOMContentLoaded",function(){document.getElementById("bootstrapApplication").addEventListener("click",function(){document.getElementById("bootstrapApplication").select()})});document.addEventListener("DOMContentLoaded",function(){document.getElementById("visitTag").addEventListener("click",function(){document.getElementById("visitTag").select()})});document.addEventListener("DOMContentLoaded",function(){document.getElementById("toggle").addEventListener("click",function(){toggleSwitch()})});
document.addEventListener("DOMContentLoaded",function(){document.getElementById("tagVisit").addEventListener("click",function(){var a=document.getElementById("visitTag").value;chrome.storage.local.set({visitTag:a});chrome.tabs.query({active:!0,currentWindow:!0},function(a){chrome.tabs.sendMessage(a[0].id,{tagVisit:!0},function(a){})})})});
document.addEventListener("DOMContentLoaded",function(){document.getElementById("saveManually").addEventListener("click",function(){var a=document.getElementById("dataDtConfigForm").value;chrome.storage.local.set({dtConfig:a});a=document.getElementById("agentLocationForm").value;chrome.storage.local.set({agentLocation:a});setTextBoxDefaults();$("#accordion").accordion("option","active",0)})});
document.addEventListener("DOMContentLoaded",function(){document.getElementById("saveFullDtConfig").addEventListener("click",function(){var a=document.getElementById("fullDtConfig").value;parser=new DOMParser;xmlDoc=parser.parseFromString(a,"text/xml");var a=xmlDoc.children[0].attributes.getNamedItem("data-dtconfig").value,c=$("input[name=htmlProtocol]:checked").val()+"://"+document.getElementById("htmlHostname").value+xmlDoc.children[0].attributes.getNamedItem("src").value;chrome.storage.local.set({dtConfig:a});
chrome.storage.local.set({agentLocation:c});setTextBoxDefaults();$("#accordion").accordion("option","active",0)})});
document.addEventListener("DOMContentLoaded",function(){document.getElementById("saveBootstrap").addEventListener("click",function(){var a=$("input[name=bootstrapProtocol]:checked").val(),c=document.getElementById("bootstrapHostname").value,b=document.getElementById("bootstrapApplication").value,b=a+"://"+c+"//dynaTraceMonitor?app="+b;console.log(b);console.log("Step 1");a=a+"://"+c+"/";c=null;c=new XMLHttpRequest;c.open("GET",b,!1);c.send();b=c.responseText;b=b.split("|");if(-1<b[1].indexOf("name="))a+=
b[1].split("=")[1],console.log(a);else return console.log("Not set properly"),!1;console.log("Step 2");if(-1<b[4].indexOf("version="))a+=b[4].split("=")[1],console.log(a);else return console.log("Not set properly"),!1;console.log("Step 3");a+="_";if(-1<b[3].indexOf("featureHash="))""!=b[3].split("=")[1]?(a+=b[3].split("=")[1],console.log(a),a+="_"):console.log("No features enabled for UEM agent");else return console.log("Not set properly"),!1;console.log("Step 4");if(-1<b[5].indexOf("buildNumber="))a+=
b[5].split("=")[1],console.log(a);else return console.log("Not set properly"),!1;console.log("Step 5");a+=".js";console.log(a);console.log("Step 6");if(-1<b[2].indexOf("config="))c=decodeURIComponent(b[2].split("=")[1]),console.log(c);else return console.log("Not set properly"),!1;chrome.storage.local.set({dtConfig:c});chrome.storage.local.set({agentLocation:a});setTextBoxDefaults();$("#accordion").accordion("option","active",0)})});
$(document).ready(function(){$("#accordion").accordion({collapsible:!0,heightStyle:"content"});$(".button").button();$("#htmlProtocolSet").buttonset();$("#bootstrapProtocolSet").buttonset();setTextBoxDefaults()});